@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor USER_COLOR
skinparam classBackgroundColor PERSON_COLOR

AddressBook *---> "1" UniquePersonList

UniquePersonList ---> Person

Person *--> "1"Nric
Person *--> "1"Name
Person *--> "1"Phone
Person *--> "1"Address
Person *--> "1"Company
Person *--> "1"Rank
Person *--> "1"Salary
Person *--> Duty
Duty --> "*"LocalDate
@enduml
